# Generated by Django 5.1.4 on 2024-12-29 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_rename_user_appuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
