# Generated by Django 5.1.4 on 2024-12-29 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0004_appuser_is_active_appuser_last_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='reset_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
