# Generated by Django 5.1.4 on 2024-12-29 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0005_appuser_reset_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
