# Generated by Django 5.1.4 on 2024-12-29 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0007_remove_appuser_reset_token_appuser_groups_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppUser',
        ),
    ]
